#!/bin/bash
#BSUB -J final_project
#BSUB -q ser
#BSUB -e plog
#BSUB -o plog
#BSUB -n 1
module load intel/2018.4
module load mpi/intel/2018.4

mpirun -np 1 ./implicit -h 0.01 -dt 0.000001 -maxit 20000 -restart 0 

